TOP_INCL = $(top_srcdir)/includes
AM_CPPFLAGS = -iquote $(top_srcdir)/includes -iquote $(top_builddir)/includes \
	      -D_POSIX_C_SOURCE=200809L -D_GNU_SOURCE
AM_CFLAGS = -Wall -Wextra -Werror -std=c99 -pedantic #-fsanitize=address
# AM_LDFLAGS = -fsanitize=address
