itest_files = $(srcdir)/tests/itests/until/until_success_complex.json \
              $(srcdir)/tests/itests/until/until_fail_single.json \
              $(srcdir)/tests/itests/until/until_success_single.json \
              $(srcdir)/tests/itests/while/while_success_complex.json \
              $(srcdir)/tests/itests/while/while_success_single.json \
              $(srcdir)/tests/itests/while/while_fail_single.json \
              $(srcdir)/tests/itests/escaping/single_quote_escape.json \
              $(srcdir)/tests/itests/escaping/double_quote_escape.json \
              $(srcdir)/tests/itests/escaping/single_quote.json \
              $(srcdir)/tests/itests/escaping/double_quote.json \
              $(srcdir)/tests/itests/escaping/single_concat.json \
              $(srcdir)/tests/itests/for/for_success_single.json \
              $(srcdir)/tests/itests/for/for_fail_single.json \
              $(srcdir)/tests/itests/for/for_implicit_in_nosep_double.json \
              $(srcdir)/tests/itests/for/for_implicit_in_nosep.json \
              $(srcdir)/tests/itests/for/for_implicit_in.json \
              $(srcdir)/tests/itests/basic/eval_order_and.json \
              $(srcdir)/tests/itests/basic/newline.json \
              $(srcdir)/tests/itests/basic/negate_failed.json \
              $(srcdir)/tests/itests/basic/eval_order_and_failed.json \
              $(srcdir)/tests/itests/basic/boolean_split.json \
              $(srcdir)/tests/itests/basic/hello.json \
              $(srcdir)/tests/itests/basic/newline_multiple.json \
              $(srcdir)/tests/itests/basic/eval_order_or_failed.json \
              $(srcdir)/tests/itests/basic/empty.json \
              $(srcdir)/tests/itests/basic/negate.json \
              $(srcdir)/tests/itests/basic/eval_order_or.json \
              $(srcdir)/tests/itests/case/case_base.json \
              $(srcdir)/tests/itests/case/case_weird.json \
              $(srcdir)/tests/itests/case/case_twin.json \
              $(srcdir)/tests/itests/case/case_double.json \
              $(srcdir)/tests/itests/functions/func_nobrace.json \
              $(srcdir)/tests/itests/functions/func_redir.json \
              $(srcdir)/tests/itests/functions/func_multiline.json \
              $(srcdir)/tests/itests/functions/func_single.json \
              $(srcdir)/tests/itests/pipes/pipe_func.json \
              $(srcdir)/tests/itests/pipes/pipe_tr_chain.json \
              $(srcdir)/tests/itests/pipes/pipe_break.json \
              $(srcdir)/tests/itests/pipes/pipe_func_file.json \
              $(srcdir)/tests/itests/pipes/pipe_basic.json \
              $(srcdir)/tests/itests/pipes/pipe_tr.json \
              $(srcdir)/tests/itests/conditions/if_else.json \
              $(srcdir)/tests/itests/conditions/if_redir.json \
              $(srcdir)/tests/itests/conditions/if_running_else.json \
              $(srcdir)/tests/itests/conditions/if_running_else_failed.json \
              $(srcdir)/tests/itests/conditions/if_simple.json \
              $(srcdir)/tests/itests/redir/redir_explicit_fd.json \
              $(srcdir)/tests/itests/redir/redir_out_simple.json \
              $(srcdir)/tests/itests/redir/redir_in_simple.json \
              $(srcdir)/tests/itests/redir/redir_append.json \
              $(srcdir)/tests/itests/redir/redir_stderr.json
